export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_WEIGHT = "SET_CURRENT_WEIGHT";
export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING ";
export const WEIGHT_ERRORS= "WEIGHT_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_WEIGHT_DATA = "CLEAR_WEIGHT_DATA";
export const GET_WEIGHTS = "GET_WEIGHTS";
export const DELETE_WEIGHT = "DELETE_WEIGHT";

